swagger: "2.0"
info:
  version: "1.0.0"
  title: Language Studio API
  contact:
    email: remarcmij@gmail.com
host: localhost:9000
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /lookup/word:
    get:
      description: Lookup a word in the dictionary
      summary: Lookup word
      parameters:
        - name: Authorization
          in: header
          description: OAuth token, e.g. `Bearer xxxx`
          required: true
          type: string
        - name: term
          in: query
          description: >
            A word or a comma-separated list of words. If a list of words is provided then a result is returned for
            the first mathing word.
          required: true
          type: string
        - name: lang
          in: query
          description: Country and Language code pair, e.g. `nl-NL`
          required: false
          type: string
        - name: attr
          in: query
          description: |
            `k` for keywords only
            `r` for keywords and references
          required: false
          type: string
          enum: [k, r]
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Lemmas"
        400:
          description: Invalid query
          schema:
            $ref: "#/definitions/Message"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/Message"
  /lookup/completion:
    get:
      description: Fetch autocompletions for (partial) word
      summary: Auto completetion
      parameters:
        - name: term
          in: query
          required: true
          type: string
        - name: lang
          in: query
          required: false
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Completions'
definitions:
  Message:
    type: object
    properties:
      message:
        type: string
  Lemmas:
    type: object
    properties:
      lemmas:
        type: array
        items:
          $ref: "#/definitions/Lemma"
      more:
        type: boolean
  Lemma:
    type: object
    properties:
      id:
        type: integer
        format: int64
      word:
        type: string
      lang:
        type: string
      attr:
        type: string
      groupName:
        type: string
      dictOrder:
        type: integer
        format: int64
      homonym:
        type: integer
        format: int64
      text:
        type: string
        format: markdown
      base:
        type: string
      baseLang:
        type: string
  Completions:
    type: object
    properties:
      completions:
        type: array
        items:
          $ref: '#/definitions/Completion'
  Completion:
    type: object
    properties:
      word:
        type: string
      lang:
        type: string
      

